# Generated by Django 3.1 on 2020-10-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolekcija', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slika',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='izvodac',
            name='slika',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pjesma',
            name='slika',
            field=models.TextField(blank=True, default=''),
        ),
    ]
