# Generated by Django 3.1 on 2020-10-04 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kolekcija', '0002_auto_20201004_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='izvodac',
            name='lajkovi',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
